default_platform(:android)

platform :android do

  # before_all do
  #   ENV["FIREBASE_LOGIN_CREDENTIALS"] = "fastlane/firebase_login_creds.json"
  # end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end



end

lane :deployToFirebase do

  # Adjust the `build_type` and `flavor` params as needed to build the right APK for your setup
  gradle(task: "clean")
  
  gradle(
    task: 'assemble',
    build_type: 'debug'
  )

  firebase_app_distribution(
    app: ENV['FIREBASE_APP_ID'],
    groups: "Demo_Testers",
    android_artifact_type: "APK",
    service_credentials_file: "fastlane/firebase_login_creds.json",
    debug: true
  )
  # ...
end


