name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm ci

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true 
    
    - name: Install bundler & Fastlane
      run: |
        gem install bundler:2.3.3
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    
    - name: Install Firebase app distribution plugin
      working-directory: ./android
      run: bundle install


    - name: Upload .apk to Firebase
      working-directory: ./android
      run: bundle exec fastlane deployToFirebase
